<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Std.BuildTools.Common</RootNamespace>
        <AssemblyName>Std.BuildTools.Common</AssemblyName>
    </PropertyGroup>

</Project>
