set(TOOLCHAIN_PROCESSOR armv7)
set(TOOLCHAIN_TRIPLE armv7-unknown-linux-gnueabihf)
set(TOOLCHAIN_SYSROOT_SUBDIR armv7)
set(TOOLCHAIN_ARCH_C_FLAGS   "-march=armv7-a -mfpu=neon -mfloat-abi=hard")
set(TOOLCHAIN_ARCH_CXX_FLAGS "-march=armv7-a -mfpu=neon -mfloat-abi=hard")
include("${CMAKE_CURRENT_LIST_DIR}/linux-static.cmake")
