set(TOOLCHAIN_PROCESSOR x86)
set(TOOLCHAIN_TRIPLE i686-unknown-linux-musl)
set(TOOLCHAIN_SYSROOT_SUBDIR x86-musl)
set(TOOLCHAIN_ARCH_C_FLAGS   "-march=i686")
set(TOOLCHAIN_ARCH_CXX_FLAGS "-march=i686")
include("${CMAKE_CURRENT_LIST_DIR}/linux-musl-static.cmake")
